version: '3'
services:
  drone-server:
    image: drone/drone:latest
    ports:
      - 80:8000
      - 9000: 9000
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_ADMIN=white87332
      - DRONE_HOST=http://192.168.2.56
      - DRONE_BITBUCKET=true
      - DRONE_BITBUCKET_CLIENT=Mvmd3xU6nZgsPVwAN9
      - DRONE_BITBUCKET_SECRET=338V6Pcydxb6TBQ9e9hVy3V3bN3HCsUQ
      - DRONE_SECRET=1234qwer
    volumes:
      - /var/lib/drone
  drone-agent:
      image: drone/agent:latest
      restart: always
      depends_on:
        - drone-server
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - DRONE_SERVER=drone-server:9000
        - DRONE_SECRET=1234qwer