version: '3.3'
services:
  mongodb:
    container_name: mongo
    image: mongo:4.0.4
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  web:
    container_name: node_web
    build:
      context: .
      dockerfile: Dockerfile
    image: node_web
    image: web
    volumes:
      - ./node:/workspace/node
    ports:
      - "80:3000"
    depends_on:
      - mongodb
    links:
      - mongodb
