version: '3.3'
services:
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - /Users/tidenet/Documents/db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  web:
    container_name: wordpress
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always
