version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - /Users/yancheng/Documents/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress: 
    container_name: wordpress
    build:
      context: .
      dockerfile: Dockerfile
    image: web
    ports:
      - "3000:8080"
    depends_on:
      - mysql
    restart: always
    environment:
       WORDPRESS_DB_HOST: mysql:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress